# Generated by Django 5.0 on 2024-01-18 03:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_item_description_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='production',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
